[server]
# Port to listen on
port = 8000

# If you want the browser to open automatically on start
headless = false

# Optional: Enable "Run on Save" to auto-refresh 
# whenever you edit the python script
runOnSave = true

[browser]
# Gather usage statistics
gatherUsageStats = false